In [1]:
import pandas as pd
import numpy as np

In [16]:
datav006  = pd.read_csv('data/corona_tested_individuals_ver_006.english.csv',parse_dates=['test_date']).set_index('test_date')
datav0083  = pd.read_csv('data/corona_tested_individuals_ver_0083.english.csv',parse_dates=['test_date']).set_index('test_date')

C:\Users\Alex\AppData\Local\Temp\ipykernel_17288\129896138.py:1: DtypeWarning: Columns (7) have mixed types. Specify dtype option on import or set low_memory=False.
  datav006  = pd.read_csv('data/corona_tested_individuals_ver_006.english.csv',parse_dates=['test_date']).set_index('test_date')
C:\Users\Alex\AppData\Local\Temp\ipykernel_17288\129896138.py:2: DtypeWarning: Columns (7) have mixed types. Specify dtype option on import or set low_memory=False.
  datav0083  = pd.read_csv('data/corona_tested_individuals_ver_0083.english.csv',parse_dates=['test_date']).set_index('test_date')

In [17]:
print(datav006.index.max())
print(datav006.index.min())

2020-04-30 00:00:00
2020-03-11 00:00:00

In [18]:
print(datav0083.index.max())
print(datav0083.index.min())

2020-11-12 00:00:00
2020-03-11 00:00:00

In [19]:
datav006['2020-03-22':'2020-03-31']

,cough,fever,sore_throat,shortness_of_breath,head_ache,corona_result,age_60_and_above,gender,test_indication
test_date,,,,,,,,,
2020-03-31,0.0,0.0,0.0,0.0,0.0,negative,No,male,Other
2020-03-31,0.0,0.0,0.0,0.0,0.0,negative,No,female,Other
2020-03-31,0.0,0.0,0.0,0.0,0.0,negative,No,male,Other
2020-03-31,0.0,0.0,0.0,0.0,0.0,positive,No,female,Other
2020-03-31,1.0,0.0,0.0,0.0,0.0,negative,No,male,Abroad
...,...,...,...,...,...,...,...,...,...
2020-03-22,1.0,1.0,0.0,0.0,0.0,negative,Yes,female,Abroad
2020-03-22,1.0,1.0,1.0,0.0,1.0,negative,No,female,Abroad
2020-03-22,1.0,0.0,0.0,0.0,0.0,negative,No,female,Abroad
2020-03-22,1.0,0.0,0.0,0.0,0.0,negative,No,male,Other
2020-03-22,1.0,0.0,0.0,0.0,0.0,negative,No,male,Other

In [20]:
datav0083['2020-03-22':'2020-03-31']

,cough,fever,sore_throat,shortness_of_breath,head_ache,corona_result,age_60_and_above,gender,test_indication
test_date,,,,,,,,,
2020-03-31,0,1,0,0,1,negative,No,male,Contact with confirmed
2020-03-31,0,0,0,0,0,negative,Yes,female,Other
2020-03-31,0,0,0,0,0,negative,No,female,Other
2020-03-31,0,0,0,0,0,negative,NaN,female,Other
2020-03-31,0,0,0,0,0,negative,No,male,Other
...,...,...,...,...,...,...,...,...,...
2020-03-22,1,0,0,0,0,negative,No,male,Other
2020-03-22,1,0,0,0,0,negative,No,female,Contact with confirmed
2020-03-22,1,0,0,0,0,negative,No,female,Contact with confirmed
2020-03-22,1,1,0,0,0,positive,Yes,female,Other
2020-03-22,0,0,0,0,0,negative,No,NaN,Other